# Generated by Django 2.2.2 on 2019-08-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='Going away Party!', max_length=100),
            preserve_default=False,
        ),
    ]
