# Generated by Django 2.2.4 on 2019-08-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name_plural': 'quantities'},
        ),
    ]
