# Generated by Django 2.2.4 on 2019-08-17 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190817_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_time',
        ),
    ]
