# Generated by Django 2.2.4 on 2019-08-18 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190817_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='meat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantities', to='events.Meat'),
        ),
    ]
