version: '3.7'

services:
  web:
    build: .
    # command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY='@4=d!dy@$ft-s!pjf=49eevw#u=iea%oi!fm@$aiin48+!qz11'
      - DEBUG=True
      - ALLOWED_HOSTS=['*',]